version: "3.8"

services:
  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dev_back
    image: back:dev
    restart: always
    volumes:
      - logs:/var/log
    ports:
      - "8001:8001"
    env_file:
      - ./app/.env
    depends_on:
      - db
    networks:
      - tusdatos

  db:
    image: postgres:16
    container_name: dev_db
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - tusdatos

networks:
  tusdatos:
    driver: bridge

volumes:
  logs:
  db_data: