name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: Ejecutar pruebas con cobertura
        run: |
          coverage run -m pytest
          coverage report
          coverage xml

      - name: Publicar reporte de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: reporte-cobertura
          path: coverage.xml

